In [111]:
import pandas as pd
import numpy as np
import cmath
import time
from sympy import symbols, Eq, solve
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import math as m

# Questions

### Q.1 

In [12]:
# x4 + 2x2 + 1 = 0 = y2 + 2y + 1; y = x2
# delta(y) = 0
# y = -2/2 = -1 = x2 => x = +-sqrt(-1)
def calc_baskara():
    x = symbols('x')

    return solve(Eq(x**4 + 2*x**2 + 1, 0), x)


# Test
print(calc_baskara())

[-I, I]


### Q.2

In [17]:
def calc_complex_power(power_factor:int):

    if (power_factor == 0):
        complex_number = complex(1, 0)
    elif((power_factor % 4) == 0):
        complex_number = complex(1, 0)
    elif((power_factor % 3) == 0):
        complex_number = complex(0, -1)
    elif((power_factor % 2) == 0):
        complex_number = complex(-1, 0)
    else:
        complex_number = complex(0, 1)

    return complex_number

# Test
print(calc_complex_power(15))

-1j


### Q.3

In [16]:
def calc_complex_product(first_numb:complex, second_numb:complex):
    return first_numb * second_numb


def calc_complex_sum(first_numb:complex, second_numb:complex):
    return first_numb + second_numb


s_output = calc_complex_sum(complex(3, -1), complex(1, 4))

p_output = calc_complex_product(complex(3, -1), complex(1, 4))

print([s_output, p_output])

[(4+3j), (7+11j)]


### Q.4

In [15]:
def verify_solution(p_solution:complex, polinomial_coef:list):
    polinomial_sum = 0
    for index, val in enumerate(polinomial_coef):
        polinomial_sum += val*(p_solution ** index)

    return True if (polinomial_sum == 0) else False
 
verify_solution(complex(-1, 1), [2, 2, 1])

True


### Q.5

In [2]:
def commut_test(numb_1:complex, numb_2:complex):
    answer = {'is_sum_commut': False, 
              'is_prod_commut': False
              }
    
    if ((numb_1 + numb_2) == (numb_2 + numb_1)):
        answer['is_sum_commut'] = True

    if ((numb_1 * numb_2) == (numb_2 * numb_1)):
        answer['is_prod_commut'] = True
    
    return answer


def associative_test(numb_1:complex, numb_2:complex, numb_3:complex):
    answer = {'is_sum_associative': False, 
              'is_prod_associative': False
              }
    
    if (((numb_1 + numb_2) + numb_3) == (numb_1 + (numb_2 + numb_3))):
        answer['is_sum_associative'] = True

    if (((numb_1 * numb_2)*numb_3) == (numb_1*(numb_2*numb_3))):
        answer['is_prod_associative'] = True

    return answer


def distributive_test(numb_1:complex, numb_2:complex, numb_3:complex):
    answer = {'is_distributive': False}

    if((numb_1 * (numb_2 + numb_3))) == (numb_1 * numb_2 + numb_1 * numb_3):
        answer['is_distributive'] = True

    return answer


print([
    commut_test(complex(1, 4), complex(1, 2)), 
    associative_test(complex(1, 4), complex(1, 2), complex(3, 4)),
    distributive_test(complex(1, 4), complex(1, 2), complex(3, 4))
    ])

[{'is_sum_commut': True, 'is_prod_commut': True}, {'is_sum_associative': True, 'is_prod_associative': True}, {'is_distributive': True}]


### Q.6

In [21]:
def triang_inneq(numb_1:complex, numb_2:complex):
    return ((abs(numb_1 + numb_2)) <= (abs(numb_1) + abs(numb_2)))


def prod_equal(numb_1: complex, numb_2:complex):
    return((abs(numb_2 * numb_1)) == (abs(numb_1) * abs(numb_2)))


# Test
print([prod_equal(complex(1,2), complex(1, 1)), prod_equal(complex(1,2), complex(1, 1))])


[True, True]


### Q.7

In [7]:
def conjug_sum(numb_1:complex, numb_2:complex):
    return ((numb_1.conjugate() + numb_2.conjugate()) == ((numb_2 + numb_1).conjugate()))


def conjug_prod(numb_1:complex, numb_2:complex):
    return ((numb_1.conjugate() * numb_2.conjugate()) == ((numb_1 * numb_2).conjugate()))

# Test
print([conjug_sum(complex(1, 2), complex(3, 4)), conjug_prod(complex(1, 2), complex(3, 4))])

[True, True]


### Q.8

In [13]:
print([complex(2, -1) + complex(1, 1), complex(2, -1) + complex(-1, -1)])

[(3+0j), (1-2j)]


### Q.9

In [12]:
# output: (modulus, phase)

def calc_geo(numb_1:complex, numb_2:complex):
    return cmath.polar(numb_1 + numb_2)


print([calc_geo(complex(2, -1), complex(1, 1)), calc_geo(complex(2, -1), complex(-1, -1))])

[(3.0, 0.0), (2.23606797749979, -1.1071487177940904)]


### Q.10

In [21]:
def polar_conv(numb_1:complex):
    rho = np.sqrt((numb_1.real**2 + numb_1.imag**2))

    if (numb_1.real == 0):
        theta = np.pi * numb_1.imag / (2 * abs(numb_1.imag))
    else:
        theta = np.arctan(numb_1.imag / numb_1.real)

    return (rho, theta)

# Test
polar_conv(complex(1, 2))

(2.23606797749979, 1.1071487177940904)

### Q.11

In [202]:
def plot_complex(numb_1:complex):

    fig = go.Figure(
        data = go.Scatterpolargl(r=np.array(cmath.polar(numb_1)[0]), theta=np.array(cmath.polar(numb_1)[1]), mode='markers', thetaunit='radians'),
        layout = go.Layout(
            title="Z(0)",
            updatemenus=[dict(
            type="buttons",
            buttons=[dict(label="Play",
                          method="animate",
                          args=[None])])],
    ),
        frames = [go.Frame(
                    data=[
                        go.Scatterpolargl(r=np.linspace(cmath.polar(numb_1)[0], cmath.polar(numb_1 * numb_1.real)[0], num=100, endpoint=True), 
                                    theta=np.linspace(cmath.polar(numb_1)[1], cmath.polar(numb_1 * numb_1.real)[1], num=100, endpoint=True), 
                                    mode='markers',
                                    thetaunit='radians')
                        ],
                    layout = go.Layout(title_text="Z(0) * Re(Z(0))")
                    ),
                go.Frame(
                    data=[
                        go.Scatterpolargl(r=np.linspace(cmath.polar(numb_1)[0], cmath.polar(numb_1 * numb_1.imag)[0], num=100, endpoint=True), 
                                    theta=np.linspace(cmath.polar(numb_1)[1], cmath.polar(numb_1 * complex(0, numb_1.imag))[1], num=100, endpoint=True), 
                                    mode='markers',
                                    thetaunit='radians')
                        ],
                    layout = go.Layout(title_text="Z(0) * Im(Z(0))"),
                )
        ]   
)

    fig.show()


plot_complex(complex(1,2))

### Q.12

In [207]:
def plot_power(numb_1: complex):
    frames = []
    for n in range(1, 11):
        r_list = []
        theta_list = []
        for i in range(1, n + 1):
            polar = cmath.polar(numb_1 ** i)
            r_list.append(polar[0])
            theta_list.append(polar[1])
        frames.append(
            go.Frame(
                data=[
                    go.Scatterpolargl(
                        r=r_list,
                        theta=theta_list,
                        mode="markers",
                        thetaunit="radians",
                    )
                ],
                layout=go.Layout(title_text=f"Z^{n}"),
            )
        )

    fig = go.Figure(
        data=go.Scatterpolargl(
            r=np.array(cmath.polar(numb_1)[0]),
            theta=np.array(cmath.polar(numb_1)[1]),
            mode="markers",
            thetaunit="radians",
        ),
        layout=go.Layout(
            title="Z(0)",
            updatemenus=[
                dict(
                    type="buttons",
                    buttons=[
                        dict(
                            label="Play",
                            method="animate",
                            args=[None],
                        )
                    ],
                )
            ],
        ),
        frames=frames,
    )

    fig.show()


plot_power(complex(2, 1))

### Q.13

In [208]:
def plot_sum(numb_1: complex, i0:complex):
    frames = []
    for n in range(1, 11):
        r_list = []
        theta_list = []
        for i in range(1, n + 1):
            polar = cmath.polar(numb_1 + n*i0)
            r_list.append(polar[0])
            theta_list.append(polar[1])
        frames.append(
            go.Frame(
                data=[
                    go.Scatterpolargl(
                        r=r_list,
                        theta=theta_list,
                        mode="markers",
                        thetaunit="radians",
                    )
                ],
                layout=go.Layout(title_text=f"Z + {i0 ** n}"),
            )
        )

    fig = go.Figure(
        data=go.Scatterpolargl(
            r=np.array(cmath.polar(numb_1)[0]),
            theta=np.array(cmath.polar(numb_1)[1]),
            mode="markers",
            thetaunit="radians",
        ),
        layout=go.Layout(
            title="Z(0)",
            updatemenus=[
                dict(
                    type="buttons",
                    buttons=[
                        dict(
                            label="Play",
                            method="animate",
                            args=[None],
                        )
                    ],
                )
            ],
        ),
        frames=frames,
    )

    fig.show()


plot_sum(complex(2, 1), complex(0, 1))

### Q.14

In [28]:
def moebius_transf(a:complex, b:complex, c:complex, d:complex):
    if ((a*d - c*b) == 0):
        return("Condition not satisfied")
    
    x = symbols('x')
    R = symbols('R(x)')
    
    return (Eq((a*x + b)/(c*x + d), R))


moebius_transf(0, 1, 1, 0)

Eq(1/x, R(x))

### Q.15

In [13]:
# O problema supõe matriz quadrada

def subspace_sum(matrix_a:np.array, matrix_b:np.array):
    return (matrix_a + matrix_b)


def subspace_inv(matrix_a:np.array):
    return np.linalg.inv(matrix_a)


def subspace_contraction(matrix_a:np.array, factor:complex):
    return factor*matrix_a

print(subspace_sum(
    np.array([[1, 2, 3], 
             [4, 5, 6]]),
    np.array([[7, 8, 9],
             [10, 11, 12]])
             ))

print(subspace_inv(
    np.array([[1, 2], 
             [3, 4]]),
             ))

print(subspace_contraction(
    np.array([[1, 2, 3], 
             [4, 5, 6]]),
             5
             ))


[[ 8 10 12]
 [14 16 18]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 5 10 15]
 [20 25 30]]


### Q.16

In [9]:
def find_transpose(matrix_a:np.array):
    return matrix_a.transpose()


def find_conjugate(matrix_a:np.array):
    return matrix_a.conjugate()


def find_dagger(matrix_a:np.array):
    return find_conjugate(find_transpose(matrix_a))


print(find_transpose(
    np.array([
        [1, complex(1, 2)],
        [2, complex(3, 5)]
    ])
))

print(find_conjugate(
    np.array([
        [1, complex(1, 2)],
        [2, complex(3, 5)]
    ])
))

print(find_dagger(
    np.array([
        [1, complex(1, 2)],
        [2, complex(3, 5)]
    ])
))

[[1.+0.j 2.+0.j]
 [1.+2.j 3.+5.j]]
[[1.-0.j 1.-2.j]
 [2.-0.j 3.-5.j]]
[[1.-0.j 2.-0.j]
 [1.-2.j 3.-5.j]]


### Q.17

In [18]:
# Frobenius Inner Product using vectorized operation

def vec_inner_product(matrix_a:np.array, matrix_b:np.array):
    return find_dagger(matrix_a.flatten()).dot(matrix_b.flatten())


print(vec_inner_product(
    np.array([
        [1, complex(1, 2)],
        [complex(3, 4), 2]
    ]),
    np.array([
        [complex(5, 6), 3],
        [complex(7, 8), 4]
    ])
))

(69-4j)


### Q.18

In [24]:
# Frobenius Inner Product using trace operation

def trace_inner_product(matrix_a:np.array, matrix_b:np.array):
    return np.trace(find_dagger(matrix_a).dot(matrix_b))


print(trace_inner_product(
    np.array([
        [1, complex(1, 2)],
        [complex(3, 4), 2]
    ]),
    np.array([
        [complex(5, 6), 3],
        [complex(7, 8), 4]
    ])
))

(69-4j)


### Q.19

In [26]:
# Test hermitian matrix

def is_hermitian(matrix_a:np.array):
    return (trace_inner_product(matrix_a, matrix_a)) == (np.trace(matrix_a.dot(matrix_a)))


print(is_hermitian(
    np.array([
        [1, complex(4, 3)],
        [complex(4, -3), 5]
    ])
))

True


### Q.20

In [52]:
# Expects an square matrix

def is_unitary(matrix_a:np.array):
    return ((
        (find_dagger(matrix_a).dot(matrix_a) == matrix_a.dot(find_dagger(matrix_a))).all() and
         (matrix_a.dot(find_dagger(matrix_a)) == np.identity(len(matrix_a))).all()
    ))


print(is_unitary(
    1/2*np.array([
        [complex(1, -1), complex(1, 1)],
        [complex(1, 1), complex(1, -1)]
    ])
))

True


### Q.21

In [61]:
# For our propose, tensorial product is actually hte Kronecker product 

def calc_tensor_prod(matrix_a:np.array, matrix_b:np.array):
    return np.kron(matrix_a, matrix_b)


print(calc_tensor_prod(
    np.array([
        [1, complex(1, 2)],
        [complex(3, 4), 2]
    ]),
    np.array([
        [complex(0, 1), 3],
        [0, complex(1, 3)]
    ])
))

[[ 0. +1.j  3. +0.j -2. +1.j  3. +6.j]
 [ 0. +0.j  1. +3.j  0. +0.j -5. +5.j]
 [-4. +3.j  9.+12.j  0. +2.j  6. +0.j]
 [ 0. +0.j -9.+13.j  0. +0.j  2. +6.j]]
